[package]
name = "k8pk"
version = "0.2.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml_ng = "0.10"
thiserror = "1.0"
dirs-next = "2.0"
which = "8.0"
inquire = "0.7"
globset = "0.4"
atty = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
